In [30]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('SalaryData_Train.csv')
df

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [4]:
df.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [5]:
df.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [6]:
df.duplicated().sum()

3258

In [7]:
feature=df.drop('sex',axis=1)
feature

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race  capitalgain  capitalloss  \
0            Adm-clerical   Not-in-family   White         2174            0   
1         Exec-managerial         Husband   White            0            0   
2       Handlers-cleaners   Not-in-family   White            0            0   
3       Handlers-cleaners         Husband   Black            0            0   
4          Prof-specialty            Wife   Black            0            0   
...                   ...             ...     ...          ...          ...   
30156        Tech-support            Wife   White            0            0   
30157   Machine-op-inspct         Husband   White            0            0   
30158        Adm-clerical       Unmarried   White            0            0   
30159        Adm-clerical       Own-child   White            0            0   
30160     Exec-managerial            Wife   White        15024            0   

       hoursperweek          native  Salary  
0                40   United-States   <=50K  
1                13   United-States   <=50K  
2                40   United-States   <=50K  
3                40   United-States   <=50K  
4                40            Cuba   <=50K  
...             ...             ...     ...  
30156            38   United-States   <=50K  
30157            40   United-States    >50K  
30158            40   United-States   <=50K  
30159            20   United-States   <=50K  
30160            40   United-States    >50K  

[30161 rows x 13 columns]

In [8]:
target=df[['sex']]
target

sex
0         Male
1         Male
2         Male
3         Male
4       Female
...        ...
30156   Female
30157     Male
30158   Female
30159     Male
30160   Female

[30161 rows x 1 columns]

In [10]:
feature=pd.get_dummies(feature,dtype=int)
feature

age  educationno  capitalgain  capitalloss  hoursperweek  \
0       39           13         2174            0            40   
1       50           13            0            0            13   
2       38            9            0            0            40   
3       53            7            0            0            40   
4       28           13            0            0            40   
...    ...          ...          ...          ...           ...   
30156   27           12            0            0            38   
30157   40            9            0            0            40   
30158   58            9            0            0            40   
30159   22            9            0            0            20   
30160   52            9        15024            0            40   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                           0                     0                   0   
1                           0                     0                   0   
2                           0                     0                   1   
3                           0                     0                   1   
4                           0                     0                   1   
...                       ...                   ...                 ...   
30156                       0                     0                   1   
30157                       0                     0                   1   
30158                       0                     0                   1   
30159                       0                     0                   1   
30160                       0                     0                   0   

       workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  ...  \
0                            0                            0  ...   
1                            0                            1  ...   
2                            0                            0  ...   
3                            0                            0  ...   
4                            0                            0  ...   
...                        ...                          ...  ...   
30156                        0                            0  ...   
30157                        0                            0  ...   
30158                        0                            0  ...   
30159                        0                            0  ...   
30160                        1                            0  ...   

       native_ Scotland  native_ South  native_ Taiwan  native_ Thailand  \
0                     0              0               0                 0   
1                     0              0               0                 0   
2                     0              0               0                 0   
3                     0              0               0                 0   
4                     0              0               0                 0   
...                 ...            ...             ...               ...   
30156                 0              0               0                 0   
30157                 0              0               0                 0   
30158                 0              0               0                 0   
30159                 0              0               0                 0   
30160                 0              0               0                 0   

       native_ Trinadad&Tobago  native_ United-States  native_ Vietnam  \
0                            0                      1                0   
1                            0                      1                0   
2                            0                      1                0   
3                            0                      1                0   
4                            0                      0                0   
...                        ...                    ...              ...   
30156                        0                      1

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
smp=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
smp

SimpleImputer(strategy='most_frequent')

In [14]:
x_train,x_test,y_train,y_test=train_test_split(feature,target,train_size=0.80,random_state=100)

In [15]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24128, 102)
(6033, 102)
(24128, 1)
(6033, 1)


In [16]:
gauss=GaussianNB()

In [17]:
gauss.fit(x_train,y_train)

C:\Users\Indranil Joshi\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [18]:
y_pred=gauss.predict(x_test)

In [19]:
accuracy_score(y_test,y_pred)

0.7992706779380077

In [20]:
bern=BernoulliNB()

In [21]:
bern.fit(x_train,y_train)

C:\Users\Indranil Joshi\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB()

In [24]:
y_pred1=bern.predict(x_test)

In [25]:
accuracy_score(y_test,y_pred1)

0.7916459472899056

In [26]:
mult=MultinomialNB()

In [27]:
mult.fit(x_train,y_train)

C:\Users\Indranil Joshi\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [28]:
y_pred2=mult.predict(x_test)

In [29]:
accuracy_score(y_test,y_pred2)

0.37576661694016245

In [31]:
confusion_matrix(y_test,y_pred1)  #Confusuion matrix for Bernoulli navie byes.

array([[1884,   96],
       [1161, 2892]], dtype=int64)

In [32]:
confusion_matrix(y_test,y_pred2)  #Confusion matrix for Multinomial naive byes.

array([[1868,  112],
       [3654,  399]], dtype=int64)

In [33]:
confusion_matrix(y_test,y_pred)   #Confusion matrix for Gaussian naive byes.

array([[1884,   96],
       [1161, 2892]], dtype=int64)

In [37]:
#Accuracy score for salary data_train using gaussian naive byes is 79.92%
#Accuracy score for salary data_train using Bernoullin naive byes is 79.16%
#Accuracy score for salary data_train using Multinomial naive byes is 37.57%

In [38]:
df1=pd.read_csv('SalaryData_Test.csv')
df1

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [39]:
df1.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  15060.000000  15060.000000  15060.000000  15060.000000  15060.000000
mean      38.768327     10.112749   1120.301594     89.041899     40.951594
std       13.380676      2.558727   7703.181842    406.283245     12.062831
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       48.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   3770.000000     99.000000

In [40]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [42]:
df1.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [43]:
df1.duplicated().sum()

930

In [49]:
target1=df[['sex']]
target1

sex
0         Male
1         Male
2         Male
3         Male
4       Female
...        ...
30156   Female
30157     Male
30158   Female
30159     Male
30160   Female

[30161 rows x 1 columns]

In [50]:
feature1=df.drop('sex',axis=1)
feature1

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race  capitalgain  capitalloss  \
0            Adm-clerical   Not-in-family   White         2174            0   
1         Exec-managerial         Husband   White            0            0   
2       Handlers-cleaners   Not-in-family   White            0            0   
3       Handlers-cleaners         Husband   Black            0            0   
4          Prof-specialty            Wife   Black            0            0   
...                   ...             ...     ...          ...          ...   
30156        Tech-support            Wife   White            0            0   
30157   Machine-op-inspct         Husband   White            0            0   
30158        Adm-clerical       Unmarried   White            0            0   
30159        Adm-clerical       Own-child   White            0            0   
30160     Exec-managerial            Wife   White        15024            0   

       hoursperweek          native  Salary  
0                40   United-States   <=50K  
1                13   United-States   <=50K  
2                40   United-States   <=50K  
3                40   United-States   <=50K  
4                40            Cuba   <=50K  
...             ...             ...     ...  
30156            38   United-States   <=50K  
30157            40   United-States    >50K  
30158            40   United-States   <=50K  
30159            20   United-States   <=50K  
30160            40   United-States    >50K  

[30161 rows x 13 columns]

In [51]:
feature1=pd.get_dummies(feature1,dtype=int)
feature1

age  educationno  capitalgain  capitalloss  hoursperweek  \
0       39           13         2174            0            40   
1       50           13            0            0            13   
2       38            9            0            0            40   
3       53            7            0            0            40   
4       28           13            0            0            40   
...    ...          ...          ...          ...           ...   
30156   27           12            0            0            38   
30157   40            9            0            0            40   
30158   58            9            0            0            40   
30159   22            9            0            0            20   
30160   52            9        15024            0            40   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                           0                     0                   0   
1                           0                     0                   0   
2                           0                     0                   1   
3                           0                     0                   1   
4                           0                     0                   1   
...                       ...                   ...                 ...   
30156                       0                     0                   1   
30157                       0                     0                   1   
30158                       0                     0                   1   
30159                       0                     0                   1   
30160                       0                     0                   0   

       workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  ...  \
0                            0                            0  ...   
1                            0                            1  ...   
2                            0                            0  ...   
3                            0                            0  ...   
4                            0                            0  ...   
...                        ...                          ...  ...   
30156                        0                            0  ...   
30157                        0                            0  ...   
30158                        0                            0  ...   
30159                        0                            0  ...   
30160                        1                            0  ...   

       native_ Scotland  native_ South  native_ Taiwan  native_ Thailand  \
0                     0              0               0                 0   
1                     0              0               0                 0   
2                     0              0               0                 0   
3                     0              0               0                 0   
4                     0              0               0                 0   
...                 ...            ...             ...               ...   
30156                 0              0               0                 0   
30157                 0              0               0                 0   
30158                 0              0               0                 0   
30159                 0              0               0                 0   
30160                 0              0               0                 0   

       native_ Trinadad&Tobago  native_ United-States  native_ Vietnam  \
0                            0                      1                0   
1                            0                      1                0   
2                            0                      1                0   
3                            0                      1                0   
4                            0                      0                0   
...                        ...                    ...              ...   
30156                        0                      1

In [52]:
feature1.isnull().sum()

age                      0
educationno              0
capitalgain              0
capitalloss              0
hoursperweek             0
                        ..
native_ United-States    0
native_ Vietnam          0
native_ Yugoslavia       0
Salary_ <=50K            0
Salary_ >50K             0
Length: 102, dtype: int64

In [53]:
gauss1=GaussianNB()
bern1=BernoulliNB()
mult1=MultinomialNB()

In [54]:
x_train,x_test,y_train,y_test=train_test_split(feature1,target1,train_size=0.75,random_state=100)

In [55]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(22620, 102)
(7541, 102)
(22620, 1)
(7541, 1)


In [56]:
gauss1.fit(x_train,y_train)

C:\Users\Indranil Joshi\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [58]:
y_pred=gauss1.predict(x_test)

In [59]:
accuracy_score(y_test,y_pred)  #Accuracy score for salary data_test for Gaussian navie byes.

0.7992308712372365

In [60]:
confusion_matrix(y_test,y_pred)  #Confusion matrix for salary data_test for Gaussian navie byes.

array([[2238,  213],
       [1301, 3789]], dtype=int64)

In [61]:
bern1.fit(x_train,y_train)

C:\Users\Indranil Joshi\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BernoulliNB()

In [62]:
y_pred=bern1.predict(x_test)

In [63]:
accuracy_score(y_test,y_pred)  #Accuracy score  for salary data_test for Bernoulli navie byes.

0.7910091499801087

In [64]:
confusion_matrix(y_test,y_pred)  #Confusion matrix for salary data_test for Bernoulli navie byes.

array([[2331,  120],
       [1456, 3634]], dtype=int64)

In [65]:
mult1=MultinomialNB()

In [66]:
mult1.fit(x_train,y_train)

C:\Users\Indranil Joshi\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [67]:
y_pred=mult1.predict(x_test)

In [68]:
accuracy_score(y_test,y_pred)  #Accuracy score for salary dat_test for multinomial naive byes.

0.371966582681342

In [69]:
confusion_matrix(y_test,y_pred)  #Confusion matrix for salary data_test for multinomial navie byes.

array([[2300,  151],
       [4585,  505]], dtype=int64)

In [1]:
#Accuracy score  for salary data_test for Gaussian navie byes is 79.92%.
#Accuracy score  for salary data_test for Bernoulli navie byes is 79%.
#Accuracy score  for salary data_test for Multinomial navie byes is 37%.